fix(lscq): add write barrier for LSCQ Pointer
bytedance/gopkg pull request #80
Opened 2021-09-03 03:38 UTC by zhangyunhao116

The Go compiler will not insert write barrier for CAS2 automatically, this PR add write barrier for both CAS2 (Enqueue) and `resetNode` (dequeue).

2021-09-06 05:21 UTC, luchsh requested changes

2021-09-06 05:21 UTC, luchsh commented on collection/lscq/asm.go
> +func runtimeEnableWriteBarrier() bool
相比较于暴露其他runtime接口，把writebarrier相关的代码暴露出来风险更高；如果CAS这块儿是核心性能来源的话，我们可以通过64bits CAS实现这个代码吗？

比如scqNodePointer里面存32位的offset，最终的指针需要用base+offset来确定，base的话可以每个q分配一块，在Node数量有限的情况下（<4GB个），应该可以实现一个64bits保存俩指针吧？
> 另外指针都按照8bytes对齐后，可以忽略低位3个bits，这样32位offset可以实际容纳32g个指针，应该足够了吧。

这样做潜在的问题是需要多一次间接寻址代价，不过base地址如果一直在cache里，实际的memory load操作并没有变多。

2021-09-06 06:22 UTC, zhangyunhao116 commented on collection/lscq/asm.go
> +func compareAndSwapUint128(addr *uint128, old1, old2, new1, new2 uint64) (swapped bool)
这里其实是Go的类型转换问题，我们已知这些 Node 和 uint128 内存排序是一致的，但是在 Node（Pointer 类型） 转成 uint128 的时候性能下降会比较严重，新的方式复用了 uint128 的接口，所以直接用里面的 fields 而不是一个新的 struct 性能更好。
（从汇编角度来说改动前后完全一致，因为内存顺序是一致的）

2021-09-06 06:41 UTC, zhangyunhao116 commented on collection/lscq/asm.go
> +func runtimeEnableWriteBarrier() bool
这个思路没问题，但是如果考虑下边界条件，其实就变成了另一种方式。因为我们其实使用 offset 的形式来存储新的 Pointer，所以要满足两个条件 1) offset 必须递增 2) 当我们新的空间中没有地方存储足够 Node 的情况下需要返回空，而不是持续增加 offset（livelock）。这些边界情况最终使得我们的方案演变成这样一种形式，也就是论文中描述地那样

即我们有两个 Queue （CAS 64bit），aq 和 fq，aq 开始为空，fq 开始为 full ，额外的空间我们简称为 extra，dq 中最开始存储的实际是 extra 的所有 index，这样每次 Enqueue 的时候先从 fq dequeue，得到一个 index，然后取 extra 里面相应的 slot 存储值，然后向 aq 中 enqueue 这个 index。dequeue 的方式则和 enqueue 相反，这样就是 CAS 64 bit 的组成。

可以看到，每次我们 enqueue 或者 dequeue 都需要两次 CAS +  FAA，实际上性能相当于之前 cas 128 bit 的一半。之前试验的代码位于 https://github.com/zhangyunhao116/lscqtest/blob/master/lscq2.go，不过 writebarrier 实在麻烦，我后面花一些时间看看能不能专门优化下这个方案。

2021-09-06 09:49 UTC, zhangyunhao116 commented on collection/lscq/asm.go
> +func runtimeEnableWriteBarrier() bool
实验了下，基本把所有优化应用进去了，看上去由于理论上的限制，速度大概只有之前的 30% ~ 60%，即 CAS 128bit 比两个 cas 64bit 快 1.5x ~ 3x 
```
name                                time/op
Uint64/EnqueueOnly/LSCQ-16          22.7ns ± 2%
Uint64/EnqueueOnly/LSCQ2-16         58.0ns ±25%
Uint64/DequeueOnlyEmpty/LSCQ-16     1.32ns ±18%
Uint64/DequeueOnlyEmpty/LSCQ2-16    1.24ns ±13%
Uint64/Pair/LSCQ-16                 30.3ns ± 1%
Uint64/Pair/LSCQ2-16                48.3ns ± 0%
Uint64/50Enqueue50Dequeue/LSCQ-16   16.1ns ± 2%
Uint64/50Enqueue50Dequeue/LSCQ2-16  25.6ns ± 1%
Uint64/30Enqueue70Dequeue/LSCQ-16   51.8ns ± 1%
Uint64/30Enqueue70Dequeue/LSCQ2-16  56.2ns ± 0%
Uint64/70Enqueue30Dequeue/LSCQ-16   18.8ns ± 2%
Uint64/70Enqueue30Dequeue/LSCQ2-16  51.0ns ±28%
```

2021-09-08 09:52 UTC, luchsh approved these changes

2021-09-08 10:21 UTC, PureWhiteWu approved these changes

2021-09-08 10:21 UTC, merged